django_main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myapp/urls.py
from django.urls import path
from . import views
app_name = 'myapp'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('testlarim/', views.testlarim, name='testlarim'),
    path('admin_user/', views.admin_user, name='admin_user'),
]

fast_api_account/models.py
from sqlalchemy import Column, Integer, String, Boolean, DateTime
from .database import Base

class AuthUser(Base):
    __tablename__ = "myapp_authuser"   # Django jadvali

    id = Column(Integer, primary_key=True, index=True)
    password = Column(String(128))
    last_login = Column(DateTime)
    is_superuser = Column(Boolean)
    username = Column(String(150))
    first_name = Column(String(150))
    last_name = Column(String(150))
    email = Column(String(254))
    is_staff = Column(Boolean)
    is_active = Column(Boolean)
    # phone = Column(String(15))
    date_joined = Column(DateTime)

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import random
# Create your models here.
class AuthUser(AbstractUser):
    phone = models.CharField(max_length=15, unique=True)
    # password = models.CharField(max_length=128)
    # email = models.EmailField(unique=True)

    # def __str__(self):
    #     return self.username
def get_unique_test_id():
    while True:
        number = random.randint(50000000, 90000000)
        if not Testlar.objects.filter(test_id=number).exists():
            return number

class Testlar(models.Model):
    user = models.ForeignKey(AuthUser, on_delete=models.CASCADE)
    test_id = models.IntegerField(default=get_unique_test_id, unique=True)
    nom = models.CharField(max_length=100)
    fan = models.CharField(max_length=100)
    tavsif = models.TextField()
    public = models.BooleanField(default=True)
    def __str__(self):
        return self.nom

myapp/views.py
from django.shortcuts import render, redirect
# from jwt_auth import jwt_required
from django_main.jwt_auth import jwt_required
from django.http import JsonResponse
from django.contrib.auth.models import User
from .models import AuthUser, Testlar
from django_main.settings import fast_api_account_domain
# from django_main.auth_backend import a
# Create your views here.
@jwt_required
def home(request):

    # user = AuthUser.objects.all()
    # for u in user:
    #     print(u.username, flush=True)
    # print('login', request.user_jwt)
    # login_s = 
    print(request.user_jwt, flush=True)
    if request.user_jwt:
        print('user authenticated', flush=True)
    # jwt_required(request.)
        return render(request, 'user/home.html')
        # return render(request, 'simple_user/home.html')
    else:
        print('user not authenticated', flush=True)
        return render(request, 'simple_user/home.html', {'fast_api_account_domain': fast_api_account_domain})

def login(request):
    return render(request, 'simple_user/login.html', {'fast_api_account_domain': fast_api_account_domain})
def register(request):
    return render(request, 'simple_user/register.html', {'fast_api_account_domain': fast_api_account_domain})
def logout_view(request):
    return render(request, 'simple_user/login.html')

@jwt_required
def testlarim(request):
    print(request.user_jwt, flush=True)
    user_id = AuthUser.objects.get(username=request.user_jwt).id
    testlar = Testlar.objects.filter(user_id = user_id).all()
    return render(request, 'user/testlarim.html' , {
        'testlar': testlar
    })

def admin_user(request):
    if request.method == 'POST':
        if 'delete' in  request.POST:
            user_id = request.POST.get('delete')
            AuthUser.objects.filter(id=user_id).delete()
            return redirect('myapp:admin_user')

    users= AuthUser.objects.all()
    return render(request, 'admin/users.html', {
        'users': users
    })

myapp/templates/simple_user/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/gif" href="{% static 'logo.gif' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <title> 
        {% block title %}Testlar{% endblock %}
    </title>

<style>
    body{
        margin: 0;
        padding: 0;
        font-family: Arial, Helvetica, sans-serif;
    }
    nav{
        display: flex;
        position: fixed;
        width: calc(100% - 100px);
        top: 0;
        left: 0;
        align-items: center;
        justify-content: space-between;
        padding: 10px 50px;
        background-color: white;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        z-index: 100;
    }
    nav .home_div_a{
        display: flex;
        gap: 20px;
        align-items: center;
        list-style: none;
        text-decoration: none;
    }
    nav .home_div_a h2{
        background: linear-gradient(45deg, rgb(170, 0, 218), aqua);
        /* background-clip: text; */
        color: white;
        padding: 5px 15px;
        border-radius: 5px;
        font-size: 25px;
        margin: 0;
    }
    a{
        text-decoration: none;
        color: black;
    }
    ul, li, a{
        text-decoration: none;
        list-style: none;
        padding: 0;
        margin: 0;
    }
    nav .home_div_a img{
        border-radius: 50%;
    }
    nav ul{
        list-style: none;
        display: flex;
        gap: 30px;
    }
    .active_page{
        background: linear-gradient(45deg, rgb(170, 0, 218), aqua);
        color: white;
    }
    nav ul a{
        padding: 10px 30px;
        background: linear-gradient(45deg, rgb(170, 0, 218), aqua);
        background-clip: text;
        color: transparent;
        font-size: 20px;
        border-radius: 5px;
    }
    #sing_up_a{
        border: 2px solid rgb(151, 7, 218);
        color: rgb(151, 7, 218);
        border-radius: 0;
        /* margin-left: 30px; */
    }
    #sing_up_a:hover{
        background: rgb(151, 7, 218);
        color: white;
    }
    
    nav ul a:hover{
        background: linear-gradient(45deg, rgb(170, 0, 218, 0.5), rgba(0, 255, 255, 0.5));
        color: white;
    }
    
    .margin_div{
        height: 70px;
        background-color: rgb(255, 255, 255);
    }

    .menu-icon{
        display: none;
    }
    @media (max-width: 780px) {
        nav{
            width: calc(100% - 40px);
            padding: 10px 20px;
        }
        .menu-icon{
            display: block;
            cursor: pointer;
            padding: 10px 15px;
        }
        .menu-icon:hover{
            background-color: rgb(225, 248, 255);
            /* padding: ; */
        }
        .menu-icon div{
            width: 25px;
            height: 3px;
            background-color: black;
            margin: 5px 0;
            transition: all 0.3s linear;
        }
        nav ul{
            position: absolute;
            top: 70px;
            left: 0;
            width: 100%;
            background-color: white;
            flex-direction: column;
            align-items: center;
            /* text-align: center; */
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.3s ease-out;
        }
        nav ul.show{
            max-height: 300px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.2);
            /* text-align: center; */
        }
        nav ul li{
            margin: 15px 0;
            /* background-color: red; */
        }
    }
    
</style>

</head>
<body>

    <nav>
        <a class="home_div_a" href="">
            <img src="{% static 'logo.gif' %}" alt="Logo" width="50" height="50">
            <h2>
                TestVix
            </h2>
        </a>
        <div class="menu-icon" onclick="menu_icon_func()">
            <div class="menu_icon_1"></div>
            <div class="menu_icon_2"></div>
            <div class="menu_icon_3"></div>
        </div>
        <ul class="">
            <li><a href="{% url 'myapp:home' %}" class="active_page" >Testlar</a></li>
            <li><a href="{% url 'myapp:login' %}">Login</a></li>
            <li><a href="{% url 'myapp:register' %}" id="sing_up_a">Sing up</a></li>
        </ul>
    </nav>
    <div class="margin_div"></div>
    {% block content %}{% endblock %}

    <script>

        function menu_icon_func(){
            const nav_ul = document.querySelector('nav ul');
            nav_ul.classList.toggle('show');
            document.querySelector('.menu_icon_1').style.transform = nav_ul.classList.contains('show') ? 'rotate(45deg) translate(5px, 5px)' : 'rotate(0) translate(0, 0)';
            document.querySelector('.menu_icon_2').style.opacity = nav_ul.classList.contains('show') ? '0' : '1';
            //  = nav_ul.classList.contains('show') ? 'rotate(45deg) translate(5px, 5px)' : 'rotate(0) translate(0, 0)';
            document.querySelector('.menu_icon_3').style.transform = nav_ul.classList.contains('show') ? 'rotate(-45deg) translate(5px, -5px)' : 'rotate(0) translate(0, 0)';
        }




        if (window.location.pathname === '/'){
            document.querySelectorAll('nav ul li a').forEach(el => {
                el.classList.remove('active_page');
            });
            document.querySelectorAll('nav ul li a')[0].classList.add('active_page');
        }
        if (window.location.pathname === '/login/'){
            document.querySelectorAll('nav ul li a').forEach(el => {
                el.classList.remove('active_page');
            });
            document.querySelectorAll('nav ul li a')[1].classList.add('active_page');
        }
        if (window.location.pathname === '/register/'){
            document.querySelectorAll('nav ul li a').forEach(el=>{
                el.classList.remove('active_page')
            })
            document.querySelectorAll('nav ul li a')[2].style.background = 'rgb(151, 7, 218)';
            document.querySelectorAll('nav ul li a')[2].style.color = 'white'; 

        }
    </script>
</body>
</html>

myapp/templates/simple_user/home.html
{% extends 'simple_user/base.html' %}
{% block title %}Testlar{% endblock %}
{% block content %}


<style>
    
    p, h2, i{
        margin: 0;
        padding: 0;
    }
    .container{
        margin: 0 auto;
        width: 100%;
        max-width: 1300px;
    }
    .cards{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
        gap: 20px;
    }
    .card{
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgb(138, 138, 138, 0.6);
        /* max-width: 300px; */
        /* width: 100%; */
        transition: 0.2s ease;
    }
    .card:hover {
    /* transform: translateY(-3px); */
    scale: 1.01;
    box-shadow: 0 4px 20px rgba(0,0,0,0.2);
}

    .id_star{
        display: flex;
        align-items: center;
        justify-content: space-between;
    }
    .id_star p{
        padding: 5px 10px;
        background-color: #0898ff;
        color: white;
        border-radius: 4px;
        font-size: 20px;
        cursor: pointer;
    }
    .id_star div{
        font-size: 20px;
    }
    .test_fani{
        font-size: 24px;
        /* color: ; */
        margin-top: 10px;
    }
    .test_tasnif{
        font-size: 18px;
        color: rgb(80, 80, 80);
        margin-top: 10px;
    }

    .user_info{
        display: flex;
        gap: 10px;
        margin-top: 10px;
    }
    .user_info h2{
        font-size: 20px;
    }
    .user_info div div{
        display: flex;
        gap: 5px;
    }
    .user_info img{
        width: 50px;
        height: 50px;
        border-radius: 50%;
        object-fit: cover;
    }
</style>
<body>
    <div class="container">
        <div class="cards">
            <div class="card">
                <div class="id_star">
                    <p>12345678</p>
                    <div>
                        <span>
                            4.5
                        </span>
                        <i class="bi bi-star">⭐️</i>
                    </div>
                </div>
                <div class="test_info">
                    <div class="test_fani">
                        <p>Test fani</p>
                    </div>
                    <div class="test_tasnif">
                        <p>Test tasnif</p>
                    </div>
                </div>
                <div class="user_info">
                    <img src="" alt="">
                    <div>
                        <div>
                            <h2>Test Nomi</h2>
                        </div>
                        <div>
                            <p>username</p>
                            <span>•</span>
                            <p>
                                5 marta
                            </p>
                            <span>•</span>
                            <p>3 oy oldin</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        let cards = document.querySelector('.cards')
        for(let i = 0; i<10; i++){
            cards.innerHTML+= `
                <div class="card">
                <div class="id_star">
                    <p>12345678</p>
                    <div>
                        <span>
                            4.5
                        </span>
                        <i class="bi bi-star">⭐️</i>
                    </div>
                </div>
                <div class="test_info">
                    <div class="test_fani">
                        <p>Test fani</p>
                    </div>
                    <div class="test_tasnif">
                        <p>Test tasnif</p>
                    </div>
                </div>
                <div class="user_info">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1TduTnXQi3ZSKVwMHsoTRUwgAX7yN7VMRoA&s" alt="">
                    <div>
                        <div>
                            <h2>Test Nomi</h2>
                        </div>
                        <div>
                            <p>username</p>
                            <span>•</span>
                            <p>
                                5 marta
                            </p>
                            <span>•</span>
                            <p>3 oy oldin</p>
                        </div>
                    </div>
                </div>
            </div>
            `
        }
    </script>
</body>
{% endblock %}

myapp/templates/simple_user/login.html
{% extends 'simple_user/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
    <style>
        body{
            background: linear-gradient(45deg, rgb(110, 2, 199), aqua);
            background-size: 100% calc(300% + 80px);
        }
        .login_container{
            position: relative;
            top: 100px;
            margin: 0 auto;
            text-align: center;
            width: 400px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.2);
            background-color: rgba(255, 255, 255, 0.281);
        }
        .login_container h2{
            margin: 0;
            margin-bottom: 20px;
            color: white;
            font-size: 30px;
        }
        .login_div{
            display: flex;
            flex-direction: column;
            gap: 15px;
        }
        .login_div div{
            display: flex;
            position: relative;
            justify-content: space-between;
        }
        .login_div input{
            width: 100%;
            padding: 10px 10px 10px 35px;
            border: 3px solid rgb(0, 46, 229);
            border-radius: 5px;
            font-size: 16px;
            outline: none;
            transition: all 0.3s linear;
        }
        .login_div input:focus{
            padding: 20px 10px 10px 35px;
        }
        .login_div input:not(:placeholder-shown){
            padding: 20px 10px 10px 35px;
        }
        .login_div label{
            position: absolute;
            top: 13px;
            left: 30px;
            background-color: rgba(255, 255, 255, 0.281);
            padding: 0 5px;
            font-size: 16px;
            color: black;
            transition: all 0.3s ease;
        }
        .login_div input:focus +label, .login_div input:not(:placeholder-shown) +label{
            top: 5px;
            font-size: 16px;
            color: rgb(0, 46, 229);
        }


        .login_div i{
            position: absolute;
            left: 10px;
            top: 20px;
            transform: translateY(-50%);
            color: rgb(0, 46, 229);
            font-size: 20px;
            transition: all 0.3s ease;
        }
        .login_div input:focus ~ i{
            top: 30px;
        }
        .login_div div a{
            font-size: 16px;
            color: white;
        }
        .login_div div a:hover{
            text-decoration: underline;
        }
        .login_div button{
            padding: 10px;
            border: none;
            background: linear-gradient(45deg, rgb(157, 0, 255), aqua 100%);
            color: white;
            font-size: 18px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .msg_show{
            color: red;
            font-size: 16px;
        }
    </style>
    <form class="login_container">
        <h2>
            Login
        </h2>
        <p class="msg_show"></p>
        <div class="login_div">
            <div>
                <input type="text" id="username" name="username" placeholder="">
                <label for="username">Username</label>
                <i class="bi bi-person"></i>
            </div>
            <div>
                <input type="password" id="password" name="password" placeholder="">
                <label for="password">Password</label>
                <i class="bi bi-lock"></i>
            </div>
            <div>
                <a href="#">Parol esdan chiqdimi</a>
                <a href="{% url 'myapp:register' %}">Sing up</a>
            </div>
            <button>
                Login
            </button>
        </div>
    </form>

<script>
    document.querySelector('.login_container').addEventListener('submit', async (e)=>{
        e.preventDefault()
        let username = document.getElementById('username').value
        let password = document.getElementById('password').value
        let res = await fetch('{{fast_api_account_domain}}/login/', {
            method : 'POST',
            credentials: "include", 
            headers: {
            'Content-Type': 'application/json'
        },
            body: JSON.stringify({
                username, password
            })
        })
        let data = await res.json()
        console.log(data);
        console.log(data.message);
        
        
        document.querySelector('.msg_show').innerHTML = data.message
        if (data.redirect){
            window.location.href = data.redirect
        }
    })
</script>

{% endblock %}

myapp/templates/simple_user/register.html
{% extends 'simple_user/base.html' %}
{% block title %} Sing Up  {% endblock %}


{% block content %}

<style>
    
    .register_container{
        width: 400px;
        margin: 0 auto;
        margin-top: 100px;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(128, 128, 128, 0.305);
        text-align: center;
    }
    .register_container h2{
        font-size: 25px;
        margin: 0;
    }
    .register_div div{
        position: relative;
        display: flex;
    }
    .register_div input{
        width: 100%;
        padding: 10px 10px 10px 20px;
        border-radius: 5px;
        outline: none;
        border: 3px solid rgb(39, 129, 255);
        margin-top: 20px;
        font-size: 20px;
    }
    .register_div label{
        position: absolute;
        top: 30px;
        left: 10px;
        font-size: 20px;
        padding: 0 10px;
        transition: all 0.3s linear;
    }
    .register_div input:focus+label, .register_div input:not(:placeholder-shown)+label{
        top: 10px;
        background-color: white;
        color: rgb(39, 129, 255);
    }
    .register_div button{
        padding: 10px;
        width: 100%;
        border-radius: 5px;
        border: 0;
        margin-top: 20px;
        background: rgb(151, 7, 218);
        color: white;
        font-size: 20px;
    }
    .msg_show{
        color: red;
        font-size: 16px;
        width: 100%;
    }
</style>


<div class="register_container">
    <h2>
        Register
    </h2>
    <form class="register_div" action="">
        <div>
            <input type="text" name="fio" id="fio" placeholder="">
            <label for="fio">First Name</label>
        </div>
        <div>
            <input type="text" name="email" id="email" placeholder="">
            <label for="email">Email</label>
        </div>
        <div>
            <input type="text" name="username" id="username" placeholder="">
            <label for="username">Username</label>
        </div>
        <div>
            <input type="text" name="password1" id="password1" placeholder="">
            <label for="password1">Password</label>
        </div>
        <div>
            <input type="text" name="password2" id="password2" placeholder="">
            <label for="password2">Return Password</label>
        </div>
        <button type="submit">
            Register
        </button>
        <div>
            <p class="msg_show"> 
            </p>
        </div>
    </form>
</div>

<script>
    // window.location.href = 'salom/'
    document.querySelector('.register_div').addEventListener('submit', async (e)=>{
        // alert('sa')
        // e.stopPropagation()
        // e.defaultPrevented()
        e.preventDefault()
        fio = document.getElementById('fio').value;
        email = document.getElementById('email').value;
        username = document.getElementById('username').value;
        password1 = document.getElementById('password1').value;
        password2 = document.getElementById('password2').value;
        let res = await fetch('{{fast_api_account_domain}}/register/', {
            method: 'POST',
            credentials: "include", 
            headers: {
            'Content-Type': 'application/json'
        },
            body: JSON.stringify({
                fio, email, username, password1, password2
            })
        })
        let data = await res.json()
        document.querySelector('.msg_show').innerHTML = data.message
        if(data.redirect){
            window.location.href = data.redirect
        }
    })
</script>

{% endblock %}

myapp/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/gif" href="{% static 'logo.gif' %}">
    <link rel="stylesheet" href=
"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <title> 
        {% block title %}Testlar{% endblock %}
    </title>

<style>
    body{
        margin: 0;
        padding: 0;
        font-family: Arial, Helvetica, sans-serif;
    }
    nav{
        display: flex;
        position: fixed;
        width: calc(100% );
        top: 0;
        left: 0;
        align-items: center;
        justify-content: space-between;
        padding: 10px 50px;
        background-color: white;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        z-index: 100;
    }
    nav .home_div_a{
        display: flex;
        gap: 20px;
        align-items: center;
        list-style: none;
        text-decoration: none;
    }
    nav .home_div_a h2{
        background: linear-gradient(45deg, rgb(170, 0, 218), aqua);
        /* background-clip: text; */
        color: white;
        padding: 5px 15px;
        border-radius: 5px;
        font-size: 25px;
        margin: 0;
    }
    a{
        text-decoration: none;
        color: black;
    }
    ul, li, a{
        text-decoration: none;
        list-style: none;
        padding: 0;
        margin: 0;
    }
    nav .home_div_a img{
        border-radius: 50%;
    }
    nav ul{
        list-style: none;
        display: flex;
        gap: 30px;
    }
    .active_page{
        background: linear-gradient(45deg, rgb(170, 0, 218), aqua);
        color: white;
    }
    nav ul a{
        padding: 10px 30px;
        background: linear-gradient(45deg, rgb(170, 0, 218), aqua);
        background-clip: text;
        color: transparent;
        font-size: 20px;
        border-radius: 5px;
    }
    #sing_up_a{
        border: 2px solid rgb(151, 7, 218);
        color: rgb(151, 7, 218);
        border-radius: 0;
        /* margin-left: 30px; */
    }
    #sing_up_a:hover{
        background: rgb(151, 7, 218);
        color: white;
    }
    
    nav ul a:hover{
        background: linear-gradient(45deg, rgb(170, 0, 218, 0.5), rgba(0, 255, 255, 0.5));
        color: white;
    }
    
    .margin_div{
        height: 70px;
        background-color: rgb(255, 255, 255);
    }

    .menu-icon{
        display: none;
    }
    @media (max-width: 780px) {
        nav{
            width: calc(100% - 40px);
            padding: 10px 20px;
        }
        .menu-icon{
            display: block;
            cursor: pointer;
            padding: 10px 15px;
        }
        .menu-icon:hover{
            background-color: rgb(225, 248, 255);
            /* padding: ; */
        }
        .menu-icon div{
            width: 25px;
            height: 3px;
            background-color: black;
            margin: 5px 0;
            transition: all 0.3s linear;
        }
        nav ul{
            position: absolute;
            top: 70px;
            left: 0;
            width: 100%;
            background-color: white;
            flex-direction: column;
            align-items: center;
            /* text-align: center; */
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.3s ease-out;
        }
        nav ul.show{
            max-height: 300px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.2);
            /* text-align: center; */
        }
        nav ul li{
            margin: 15px 0;
            /* background-color: red; */
        }
    }
    
</style>

</head>
<body>

    <nav>
        <a class="home_div_a" href="{% url 'myapp:home' %}">
            <img src="{% static 'logo.gif' %}" alt="Logo" width="50" height="50">
            <h2>
                TestVix
            </h2>
        </a>
        <div class="menu-icon" onclick="menu_icon_func()">
            <div class="menu_icon_1"></div>
            <div class="menu_icon_2"></div>
            <div class="menu_icon_3"></div>
        </div>
        <ul class="">
            <li><a href="{% url 'myapp:home' %}" class="active_page" >Testlar</a></li>
            <li><a href="{% url 'myapp:testlarim' %}">Testlarim</a></li>
            <li><a href="{% url 'myapp:home' %}">Profil</a></li>
            <li><a href="{% url 'myapp:logout' %}" id="sing_up_a" onclick="logout_func()">Chiqish</a></li>
        </ul>
    </nav>
    <div class="margin_div"></div>
    {% block content %}{% endblock %}

    <script>
        async function logout_func(){
            let res = await fetch('http://127.0.0.1:8002/logout/', {
                credentials : 'include'
            })
            let data = await res.json()
            window.location.href = data.redirect

        }
        function menu_icon_func(){
            const nav_ul = document.querySelector('nav ul');
            nav_ul.classList.toggle('show');
            document.querySelector('.menu_icon_1').style.transform = nav_ul.classList.contains('show') ? 'rotate(45deg) translate(5px, 5px)' : 'rotate(0) translate(0, 0)';
            document.querySelector('.menu_icon_2').style.opacity = nav_ul.classList.contains('show') ? '0' : '1';
            //  = nav_ul.classList.contains('show') ? 'rotate(45deg) translate(5px, 5px)' : 'rotate(0) translate(0, 0)';
            document.querySelector('.menu_icon_3').style.transform = nav_ul.classList.contains('show') ? 'rotate(-45deg) translate(5px, -5px)' : 'rotate(0) translate(0, 0)';
        }




        if (window.location.pathname === '/'){
            document.querySelectorAll('nav ul li a').forEach(el => {
                el.classList.remove('active_page');
            });
            document.querySelectorAll('nav ul li a')[0].classList.add('active_page');
        }
        if (window.location.pathname === '/testlarim/'){
            document.querySelectorAll('nav ul li a').forEach(el => {
                el.classList.remove('active_page');
            });
            document.querySelectorAll('nav ul li a')[1].classList.add('active_page');
        }
        if (window.location.pathname === '/register/'){
            document.querySelectorAll('nav ul li a').forEach(el=>{
                el.classList.remove('active_page')
            })
            document.querySelectorAll('nav ul li a')[2].style.background = 'rgb(151, 7, 218)';
            document.querySelectorAll('nav ul li a')[2].style.color = 'white'; 

        }
    </script>
</body>
</html>